close the communication threads when `GUIView.dispose` gets called
BME-MIT-IET/iet-hf-2024-bubogok pull request #15
Opened 2024-05-10 16:00 UTC by daniel-szarkowicz

Ez a PR módosítja a `MainCommunicator` főszálát és `stop` metódusát, hogy a metódus szóljon a főszálnak amikor le kell állnia. A metódust eddig semmi nem hívta meg, most már a `GUIView` `dispose` metódusa hívja meg.

2024-05-10 19:13 UTC, Szombatioi approved these changes
Noice. Máshol ha jól látom nincs már szabadon kószáló thread

2024-05-10 20:48 UTC, koczoa requested changes
Akkor nem zárjuk be a szálakat, ha grafikus felület nélkül fut a program, hiszen GUIView nélkül nincs mc.stop()

2024-05-11 10:04 UTC, daniel-szarkowicz commented
Amennyiben a JVM helyesen áll le, meg fog hívódni a `MainCommunicator::stop` és ha kell a `GUIView::dispose`. Sajnos ha `gradle run`-al futtatjuk és `SIGINT`-et (Control+C) küldünk, akkor a gradle rosszul állítja le a programot (lásd: https://github.com/gradle/gradle/issues/1109). Egy megoldás, hogy `gradle run` helyed `gradle build && java -jar`-t használunk, de #18 miatt ez jelenleg nem opció.

2024-05-21 18:26 UTC, koczoa approved these changes
lgtm

2024-05-21 18:26 UTC, merged