Added basic Logger interface & Console logger implementation
BME-MIT-IET/iet-hf-2024-bubogok pull request #17
Opened 2024-05-10 19:58 UTC by Szombatioi

Ez a PR új mappát (`logger`) adott hozzá a `test/core/src/temalab` mappához, melyben egyelőre a logger interfésze és a konzolos logger implementációja található.

Véleményeket bátran, mert régen java-ztam és nem tudom hogy kell az ilyet szépen csinálni 👉👈

(log4j-re azt találtam, hogy szörnyű és fusson ki merre lát ezért álltam neki scratchről megírni)

2024-05-10 23:00 UTC, daniel-szarkowicz reviewed
A logolás egy trükkös probléma, nem véletlenül léteznek hozzá (túl) komplex megoldások. Ha tényleg sajátot akarsz írni, akkor is ajánlom, hogy nézd meg, hogy a többi loggert hogyan kell használni, mert az segíthet a tervezésben.

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +        System.out.println(ANSI_RESET + "DEBUG("+area+"): " + message + ANSI_RESET);
A `ConsoleLogger` majd ne az `System.out`-ra írjon, hanem a `System.err`-re.

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +public class ConsoleLogger implements Logger {
A kódduplikáció csökkentése érdekében nagy valószínűséggel kelleni fog egy `StreamLogger` osztály is, ami tetszőleges `PrintSteam`/`OutputSteam`-ekre tud írni.

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +    static void d(String area, String message){}
A statikus metódusok jók lennének, de sajnos nem lehet őket overrideolni. Ha én leírom azt, hogy `Logger.d("area", "message")`, akkor honnan fogja tudni a Java, hogy most a terminálba, egy fájlba vagy a guira kerüljön a log?

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +public class ConsoleLogger implements Logger {
Sőt lehet, hogy a `StreamLogger` lesz az egyetlen logger implementáció, és ha valaki saját helyre akar logolni, akkor csak készít egy `OutputStream`-et.

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +    static final String ANSI_RESET = "\u001B[0m",
Ez lehetne `private`

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +    static final String ANSI_RESET = "\u001B[0m",
nitpick: én nem használnék többszörös változó deklarációt

2024-05-10 23:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +    static void d(String area, String message){}
A logoló függvények majd legyenek `public`-ok.

2024-05-15 20:58 UTC, Szombatioi commented
Újratervezés történt.
Interfésznek nem láttam értelmét, ezért egy `Logger` osztályt hoztam létre, ami egy `PrintStream`-re ír. Ennek átadhatunk konzolt, fájlt, stb.

A konzol színezésének ötletét elvetettem, mert Java-ban sajnos csak ANSI escape kódokkal lehet megoldani, ami belekerülne pl. egy fájlbaírásnál a fájlba. (ez megoldható lenne typecheck-kel, de na)

Felteszem fájlba több helyről is akarunk írni, ezért ennek megoldására kellene még valamilyen ötlet.

2024-05-15 22:03 UTC, daniel-szarkowicz requested changes

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +        String pkg = caller.getClass().getPackage().getName();
Szerintem a package name helyett írhatjuk a class name-t is, főleg mert az kinyerhető a stack trace-ből és akkor nem kell a konstruktorban átadni a `caller`-t.

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +        this.printStream.print(String.format("%-35s\t%-10s\t%-10s", header, pkg, function));
a padding jó ötlet, így átláthatóbb lesz a log

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +        this.printStream.println(String.format("%s - %s", label, message));
Ha a `message` több sorból áll (a `label` talán nem fog), akkor lesz olyan sor, ami rossz helyen fog kezdődni. Itt szerintem minden sort indentálni kéne vagy ki kéne rakni elé a log információt, hogy ugyan ott kezdődjenek.

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> -    static void d(String area, String message){}
az egybetűs metódusok hasznosak lehetnek, mert lusták vagyunk

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +public class Logger {
Ebből nagy valószínűséggel lesz öröklés, hogy lehessen színesen logolni a terminálba. Majd az öröklési hierarchia tetejére kerüljön egy interfész.

2024-05-15 22:03 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/Logger.java
> +    private PrintStream printStream;
Ha Enterpriseᵀᴹ kódot akarsz írni, akkor egy [`Cleaner`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ref/Cleaner.html)-el bezárhatod a `printStream`-et automatikusan amikor a GC felszabadít egy loggert.
Ha statikus/singleton lesz a logger, akkor lehet hogy egy [`shutdownHook`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Runtime.html#addShutdownHook(java.lang.Thread))-ot kéne használni.
Meg létezik még az [`AutoClosable`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/AutoCloseable.html) interfész is, de azt ránézésre ilyen "egyszer használatos" objektumokra kéne használni.
Meg van a [`finalize`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html#finalize()), de a deprekált, szóval talán az nem jó.

2024-05-15 22:12 UTC, daniel-szarkowicz commented
> A továbbiakban érdemes megfontolnunk, hogy akarunk-e Singleton-t csinálni ebből az osztályból.
> 
> Felteszem fájlba több helyről is akarunk írni, ezért ennek megoldására kellene még valamilyen ötlet. (pl. Singleton-ként ez megoldható)

Szerintem lehetne az androidos loggerhez hasonlót csinálni. Most gyorsan így csinálnám meg:
```java
public final class Log {
    private static Logger logger = new ConsoleLogger();

    public static void setLogger(Logger newLogger) {
        logger = newLogger;
    }

    public static void d(String label, String message) {
        logger.debug(label, message);
    }
}
```
Ennek az előnye az lenne, hogy olyan kényelmes meghívni, mint ha statikus metódusokat/singleton-t használnál, de könnyen cserélhető, hogy milyen implementáció van mögötte.

2024-05-16 15:23 UTC, Szombatioi commented on test/core/src/temalab/logger/Logger.java
> +public class Logger {
Nem elég az, ha magát a Logger osztályt tekintjük az öröklési hierarchia tetejének?

2024-05-16 15:26 UTC, Szombatioi commented on test/core/src/temalab/logger/Logger.java
> +public class Logger {
Vagyis igazából jól jön az interfész, ha a későbbi kommentben említett Singleton megoldást választjuk

2024-05-16 15:38 UTC, Szombatioi commented
Viszont akkor kéne egy LoggerBase osztály is, ami a Logger interfészt valósítja meg.
Erre azért volna szükség szerintem, mert az információk összegyűjtése (dátum, class name, stb.) mindenhol ugyanúgy nézne ki, ezért célszerű ebbe a Base-be beletenni egy függvényt erre a célra:
```java
public default void getInfos(String level, String label, String message) {
        protected void getInfos(String level, String label, String message) {
        String timeOfLog = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        String header = String.format("[%s - %s]", timeOfLog, level);
        String className = Thread.currentThread().getStackTrace()[1].getClass().getName(); 
        String function = Thread.currentThread().getStackTrace()[1].getMethodName()  + "()";
		
		this.printStream.print(String.format("%-35s\t%-10s\t%-10s", header, className, function));
        this.printStream.println(String.format("%s - %s", label, message));
    }
```

Emellett persze tárolná a printStreamet is

2024-05-17 10:35 UTC, daniel-szarkowicz commented
Egy absztrakt ős egy néhány segédfüggvénnyel jó ötlet. Majd a stacktrace halászatra oda kell figyelni, mert különböző implementációk különböző számú metódust hívhatnak meg a `getInfos` előtt.

2024-05-17 10:37 UTC, daniel-szarkowicz commented
A `getInfos` egy `PrintStream`-re írás helyett returnölhetne egy stringet, hogy csökkentsük a metódus függőségeit (és mellékhatásait).

2024-05-21 13:21 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/LoggerBase.java
> +    public void debug(String label, String message){}
itt használhatsz absztrakt metódust

2024-05-21 13:24 UTC, daniel-szarkowicz requested changes
A Log osztály jó, a loggereken még egy kicsit változtatni kell

2024-05-21 13:24 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/LoggerBase.java
> +    public void debug(String label, String message){}
itt használhatsz absztrakt metódust

2024-05-21 13:24 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/LoggerBase.java
> +    private PrintStream printStream = null;
ha a `LoggerBase` nem használja a `printStream`et, akkor ne is tartalmazza, mert csak egy felesleges függőség

2024-05-21 13:24 UTC, daniel-szarkowicz commented on test/core/src/temalab/logger/ConsoleLogger.java
> +            getPrintStream().println(String.format("\t%s - %s", label, line));
ez szebb lenne, ha nem getteren keresztül használná a printStreamet

2024-05-21 18:52 UTC, koczoa approved these changes
lgtm, ha amit dani kért, meglesz

2024-05-22 16:46 UTC, daniel-szarkowicz submitted a review, later dismissed

2024-05-22 19:20 UTC, darpleon approved these changes

2024-05-22 19:22 UTC, merged