a pytohn mostmár nem próbál meg egy üres listán iterálni, ha az adott…
BME-MIT-IET/iet-hf-2024-bubogok pull request #20
Opened 2024-05-12 16:36 UTC by koczoa

… csapatban nincs már egy egység sem

2024-05-12 19:38 UTC, daniel-szarkowicz requested changes

2024-05-12 19:38 UTC, daniel-szarkowicz commented on test/assets/python/test1.py
> +                        endPhase(units)
Az `endPhase`-t szerintem itt nem szabad meghívni, mert az még olvasna valami inputot. Én inkább válaszolnék egy feladás jelellel és majd a javatól kapott `endPhase`-t kezelném.

2024-05-20 16:20 UTC, daniel-szarkowicz requested changes

2024-05-20 16:20 UTC, daniel-szarkowicz commented on test/assets/python/test1.py
> +                        print("endTurn", file=sys.__stdout__, flush=True)
a print helyett én inkább a `teamCommands`-ba rankám az `endTurn`-t, hogy véletlenül se legyen kettő válasz egy kérésre

2024-05-20 16:22 UTC, daniel-szarkowicz commented
rebaseld a PRt a legújabb masterre, hogy majd tudjuk mergelni

2024-05-21 10:32 UTC, daniel-szarkowicz approved these changes

2024-05-21 10:34 UTC, matetamasi approved these changes
lgtm, mehet

2024-05-21 10:34 UTC, merged