Java win condition check
BME-MIT-IET/iet-hf-2024-bubogok pull request #21
Opened 2024-05-12 17:09 UTC by koczoa

pretty basic, but if any of the teams has zero units, it closes the program

2024-05-12 19:54 UTC, daniel-szarkowicz commented on test/core/src/temalab/communicator/Communicator.java
> +					throw new RuntimeException("out of units");
Ha befejezi a kört, akkor elfogytak a unitjai? Ezért biztos, hogy exceptiont kel dobni? Nem lehetne return?

2024-05-12 19:54 UTC, daniel-szarkowicz commented on test/core/src/temalab/communicator/Communicator.java
> +	public void communicate() throws RuntimeException {
`RuntimeException`-t nem kell kiírni, meg amúgy is lehetne helyette valami egyértelműbb.

2024-05-12 19:54 UTC, daniel-szarkowicz commented on test/core/src/temalab/common/MainModel.java
> +		System.out.println(winnerTeam + " team won!");
A játék eredményéről nem kéne értesíteni a pythonos cuccokat is?

2024-05-12 19:54 UTC, daniel-szarkowicz commented on test/core/src/temalab/common/MainModel.java
> +		System.exit(0);
Ha vége a játéknak, akkor bezárjuk a programot? Nem lehet új játékot kezdeni?

2024-05-12 19:54 UTC, daniel-szarkowicz commented on test/core/src/temalab/communicator/MainCommunicator.java
> +                            mm.winEvent(c.getTeam().getName());
az nyer, aki elrontotta a kommunikációt?

2024-05-21 14:00 UTC, daniel-szarkowicz requested changes
Ha több mint kettő csapat van, akkor most mindenki más nyerni fog. Kerüljön bele a specifikációba, hogy csak kettő csapat lehet.

2024-05-21 14:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/common/MainModel.java
> +	private mainModelCommunicatorListener mmcl;
nem lehetne érthetőbb változóneveket használni?

2024-05-21 14:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/common/MainModel.java
> +		System.exit(0);
exit helyett egy resetet kéne csinálni és újrakezdeni a szimulációt

2024-05-21 14:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/common/mainModelCommunicatorListener.java
> +public interface mainModelCommunicatorListener {
nagy betűvel kéne kezdődnie

2024-05-21 14:00 UTC, daniel-szarkowicz commented on test/core/src/temalab/communicator/MainCommunicator.java
> +    public void teamLost(String name) {
itt nem lehetne string helyett egy a csapat objektumot átadni?

2024-05-21 14:00 UTC, daniel-szarkowicz commented on test/python/test1.py
> +    sys.exit(0)
end után nem lehet új játékot kezdeni

2024-05-21 18:34 UTC, daniel-szarkowicz approved these changes
igazából jó, de ezeket az apróságokat javítsad még ki

2024-05-21 18:34 UTC, daniel-szarkowicz commented on test/core/src/temalab/gui/view/UnitView.java
> -		gv.unitDestoryed(u);
ha a unitDestroyed ezzel használatlan lett, akkor legyen kitörölve

2024-05-21 18:34 UTC, daniel-szarkowicz commented on test/python/test1.py
> +    logger.debug_print("ASDF:", result)
asdf helyett lehetne értelmesebb debug üzenet

2024-05-21 18:45 UTC, matetamasi approved these changes

2024-05-21 18:45 UTC, matetamasi commented on test/core/src/temalab/common/MainModel.java
> +	// this method should call the final thread closer as of #15
Ez még releváns? Ha nem, töröld, ha igen, implementáld.

2024-05-21 18:45 UTC, matetamasi commented on test/core/src/temalab/communicator/Communicator.java
> +			while (true) {
Ez a loop direkt lett egyel bentebb indentálva?

2024-05-21 18:45 UTC, matetamasi commented on test/core/src/temalab/gui/view/UnitView.java
> +		visible = false;
Itt nem lesz probléma ha a mezőre akar lépni egy másik unit?

2024-05-21 18:48 UTC, merged