Fix gradle tasks for desktop
BME-MIT-IET/iet-hf-2024-bubogok pull request #23
Opened 2024-05-20 18:43 UTC by matetamasi

A gradle run valamint a build taskok most már működnek desktop projektben. Az ebben, valamint a kódban hard-code-olt elérési útvonalak kiszervezésre kerültek.

2024-05-20 20:56 UTC, darpleon requested changes

2024-05-20 20:56 UTC, darpleon commented on test/core/src/temalab/gui/view/UnitView.java
> +	private static final String imagesPath = "assets/images/";
Ezt nem lehetne javás Path-al, mint a Unit.java-ban?

2024-05-20 20:56 UTC, darpleon commented on README.md
> +gradle run --args#"graf"
Itt # helyett nem = kéne?

2024-05-20 20:56 UTC, darpleon commented on test/desktop/build.gradle
> +project.ext.rootDir = new File("..")
Az ilyesmit el lehetne kerülni ha csak egy centrális build.gradle lenne

2024-05-20 22:14 UTC, matetamasi commented on test/core/src/temalab/gui/view/UnitView.java
> +	private static final String imagesPath = "assets/images/";
A Gdx.files.internal hívás során mindenképp vissza kellene konvertálni stringgé, szóval itt szerintem praktikusabb egyszerűen így tárolni.

2024-05-20 22:15 UTC, matetamasi commented on README.md
> +gradle run --args#"graf"
De igen, köszi!

2024-05-20 22:19 UTC, matetamasi commented on test/desktop/build.gradle
> +project.ext.rootDir = new File("..")
A három build.gradle egyesítése bonyolultnak tűnik, én pedig sajnos nem igazán értek a gradle-höz. Ha valaki igen, akkor valóban megcsinálhatná.

2024-05-21 08:10 UTC, daniel-szarkowicz approved these changes

2024-05-21 09:23 UTC, darpleon approved these changes
kösz

2024-05-21 09:24 UTC, merged