Add cucumber to github actions
BME-MIT-IET/iet-hf-2024-bubogok pull request #28
Opened 2024-05-21 21:06 UTC by matetamasi

2024-05-21 21:16 UTC, Szombatioi commented on test/core/test/cucumber/CucumberStepDefinitions.java
> +	@Before
Lehetséges, hogy @BeforeAll kell majd ide? Vagy a Cucumber nem támogatja?

2024-05-21 21:16 UTC, Szombatioi approved these changes
lgtm.

2024-05-21 21:20 UTC, daniel-szarkowicz reviewed
lbtm.

2024-05-22 07:25 UTC, koczoa requested changes

2024-05-22 07:25 UTC, koczoa commented on test/core/test/cucumber/CucumberStepDefinitions.java
> +		white = new Team("white", null, 0, null);
a MainModel nem lehet null

2024-05-22 07:25 UTC, koczoa commented on test/core/test/cucumber/CucumberStepDefinitions.java
> +		red = new Team("red", null, 0, null);
szerintem a strategy sem lehet null

2024-05-22 07:37 UTC, koczoa approved these changes
now okay

2024-05-22 07:37 UTC, merged